# welcome to numpy

In [1]:
import numpy as np

In [2]:
myarr=np.array([3,2,5,6,4],np.int8)

In [3]:
myarr

array([3, 2, 5, 6, 4], dtype=int8)

In [4]:
myarr.dtype

dtype('int8')

In [5]:
myarr=np.array([[3,2,5,6,4]])

In [6]:
myarr[0,1]

2

In [7]:
myarr[0,3]=45

In [8]:
myarr[0,3]

45

# array creation: using python object eg-list,tuple

In [9]:
listarr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
listarr.shape

(3, 3)

In [12]:
listarr.dtype

dtype('int32')

In [13]:
setarr=np.array({4,5,6})

In [14]:
setarr
#iska datatype object ban jata hai aur mathematicall aur efficent cal k liye interger hi use krenge

array({4, 5, 6}, dtype=object)

# array creation:using internsic method


In [15]:
zeros=np.zeros((2,5))
#YOU CAN MAKE SINGLE ARRAY

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
rng=np.arange(15)

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
lspace=np.linspace(1,4,10)

In [20]:
lspace

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [21]:
emp=np.empty((2,2))
#YOU CAN ALSO MAKE SINGLE ARRAY

In [22]:
emp

array([[2.44029516e-312, 2.05833592e-312],
       [2.14321575e-312, 1.89147405e-307]])

In [23]:
ide=np.identity(2)

In [24]:
ide

array([[1., 0.],
       [0., 1.]])

In [25]:
npr=np.arange(10)


In [26]:
reshape=npr.reshape((5,2))
#You can change single to 2d rember total element in 2d = 10

In [27]:
reshape

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [28]:
single=reshape.ravel()
#2D TO single

In [29]:
single

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Axis AND MULTIPLE SMALL FUNCTIONS

In [30]:
arr1=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [69]:
arr1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [70]:
temp=arr1.sum(axis=0)
#axis=0 se yeh srif 10+40+70,20+50+80,60+60+90, inka sum dega 

In [33]:
temp

array([120, 150, 180])

In [34]:
temp=arr1.sum(axis=1)
#10+20+30,40+50+60,70+80+90

In [35]:
temp

array([ 60, 150, 240])

In [36]:
arr1.T
#attributes

array([[10, 40, 70],
       [20, 50, 80],
       [30, 60, 90]])

In [37]:
arr1.flat
# for iteration each element

In [38]:
for i in arr1.flat:
    if(i>30):
        print(i)
    

40
50
60
70
80
90


In [39]:
arr1.ndim

2

In [40]:
arr1.size

9

In [41]:
arr1.nbytes
#total space

36

In [42]:
arr2=np.array([10,25,63,14,85,98,4,1,23])

In [43]:
arr2

array([10, 25, 63, 14, 85, 98,  4,  1, 23])

In [44]:
arr2.argmax()
#YEH FUNCTION hai

5

In [45]:
arr2.argmin()

7

In [46]:
arr2.argsort()

array([7, 6, 0, 3, 8, 1, 2, 4, 5], dtype=int64)

In [47]:
arr1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [48]:
arr1.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [49]:
arr1.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [50]:
arr1.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [51]:
arr1.argmax()

8

# MATRIX OPERATION ON ARRAY

In [52]:
arr3=np.array([[6,3,2],[4,5,6],[1,5,4]])
arr3

array([[6, 3, 2],
       [4, 5, 6],
       [1, 5, 4]])

In [53]:
arr1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [54]:
arr1+arr3

array([[16, 23, 32],
       [44, 55, 66],
       [71, 85, 94]])

In [55]:
arr1-arr3

array([[ 4, 17, 28],
       [36, 45, 54],
       [69, 75, 86]])

In [56]:
arr1*arr3

array([[ 60,  60,  60],
       [160, 250, 360],
       [ 70, 400, 360]])

In [57]:
arr3

array([[6, 3, 2],
       [4, 5, 6],
       [1, 5, 4]])

In [58]:
np.where(arr3>5)

(array([0, 1], dtype=int64), array([0, 2], dtype=int64))

In [59]:
np.count_nonzero(arr3)

9

In [60]:
np.nonzero(arr3)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

# PROOF  THAT NUMPY IS BETTER THAN PYTHON LIST TUPLE

In [61]:
import sys

In [62]:
list_py=[10,20,30]

In [63]:
array_np=np.array([list_py])

In [64]:
list_py

[10, 20, 30]

In [65]:
array_np

array([[10, 20, 30]])

In [66]:
sys.getsizeof(1)*len(list_py)

84

In [67]:
array_np.nbytes

12

In [68]:
array_np.itemsize*array_np.size

12

# SO AS U CAN SEE THAT PYTHON ARRAY TAKE 84 BYTES WHERAS
# NUMPY ARRAY TAKE ONLY 12 BYTES

In [72]:
my=np.array([[1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]])

In [73]:
my

array([[1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [74]:
my.shape

(4, 3)